##### THIS FILE IS NO LONGER IN USE #####
# To make changes to the harvester's configuration modify this file instead.
# https://github.com/cessda/cessda.cdc.aggregator.deploy/blob/main/charts/harvester/config/config.yaml
