logging:
  file: '@logging.file@'
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\)) - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\)) - %message%n'
  level:
    org:
      springframework: '@logging.level.org.springframework@'
    de.codecentric.boot.admin: DEBUG
    springfox.documentation.spring.web.readers.operation: WARN
harvester:
  dir: '@documents@'
  timeout: 100s
  keepOAIEnvelope: true
  removeOAIEnvelope: true
  repos:
   # Changed metadata prefix. See #388
    - url: https://www.adp.fdv.uni-lj.si/v0/oai
      code: ADP
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi_c
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    # Changed metadata prefix. See #388
    - url: http://194.117.18.18:6003/v0/oai
      code: APIS
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi_c
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://data2.aussda.at/oai
      code: AUSSDA
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi_c
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    # Temporarily excluded, see #372
    # - url: http://nesstar.soc.cas.cz/oai-pmh/
    #  code: CSDA
    # metadataPrefixes: oai_ddi 
    - url: https://easy.dans.knaw.nl/oai/
      code: DANS
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25_en
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
        - metadataPrefix: oai_ddi25_nl
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    # Changed metadata prefix. See #388
    - url: https://kuha.sa.dk/v0/oai
      code: DNA
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi_c
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: http://services.fsd.uta.fi/v0/oai
      code: FSD
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://dbkapps.gesis.org/dbkoai
      code: GESIS
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://oai-pmh.nsd.no/oai-pmh/
      code: NSD
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi
          ddiVersion: NESSTAR
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    # Temporarily excluded, has same content as ProgedoCDSP
    #- url: https://data.sciencespo.fr/oai
    #  code: ProgedoSciencesPo
    #  metadataPrefixes: oai_ddi
    #  sets: CDSP
    # Added endpoint (see #403)
    - url: https://data.progedo.fr/oai
      code: ProgedoCDSP
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
      # Test endpoint for EQB
    - url: https://explore.cdsp.sciences-po.fr/oai/request
      code: ProgedoSciencesPo
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi32
          ddiVersion: DDI_3_2
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-3.2/latest/profile.xml
    # Changed metadata prefix. See #388
    - url: http://147.213.4.44:6003/v0/oai
      code: SASD
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi_c
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://snd.gu.se/en/oai-pmh 
      code: SND
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25
          setSpec: subject:social-sciences
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://www.sodha.be/oai
      code: SODHA
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi
          ddiVersion: DDI_2_5
          setSpec: SODHA_CDC
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://datacatalogue.sodanet.gr/oai
      code: SoDaNet
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
      code: UKDS
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: ddi
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    - url: http://oai.unidata.unimib.it/v0/oai
      code: UniData
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi25
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
