harvester:
  incremental: false
  dir: '@documents@'
  recipient: support@cessda.eu
  repos:
  - url: https://datacatalogue.cessda.eu/oai-pmh/v0/oai
    code: CESSDA
    metadataPrefixes:
      - metadataPrefix: oai_ddi25
        setspec: openaire_data
        ddiVersion: 2_5
