logging:
  file: '@logging.file@'
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\)) - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\)) - %message%n'  
  level:
    org:
      springframework: '@logging.level.org.springframework@'
    de.codecentric.boot.admin: DEBUG
    springfox.documentation.spring.web.readers.operation: WARN
harvester:
  metadataFormat: ddi
  dialectDefinitionName: gesisCMM-ddi122
  dir: '@documents@'
  recipient: john.shepherdson@essex.ac.uk,toni.sissala@tuni.fi
  timeout: 100s
  keepOAIEnvelope: true
  removeOAIEnvelope: true
  from:
    single: '1800-01-01'
    initial: '0001-01-01'
    incremental: '2017-02-28'
    full: '1901-01-01'
  cron:
    incremental: 0 0 */2 * * *
    full: 00 31 12 * * ?
  repos:
    - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
      metadataFormat: ddi
    - url: https://kuha.sa.dk/v0/oai
      metadataFormat: oai_ddi25
    - url: http://194.117.18.18:6003/v0/oai
      metadataFormat: oai_ddi25
    - url: http://services.fsd.uta.fi/v0/oai
      metadataFormat: oai_ddi25
    - url: https://dbkapps.gesis.org/dbkoai3
      metadataFormat: oai_ddi25
    - url: http://147.213.4.44:6003/v0/oai
      metadataFormat: oai_ddi25
    - url: https://snd.gu.se/en/oai-pmh?set=discipline:social-science
      metadataFormat: oai_ddi25
    - url: https://easy.dans.knaw.nl/oai/
      metadataFormat: oai_ddi25_en
    - url: https://easy.dans.knaw.nl/oai/
      metadataFormat: oai_ddi25_nl
    - url: https://data2.aussda.at/oai
      metadataFormat: oai_ddi
    - url: https://nesstar2.adp.fdv.uni-lj.si/oai-pmh/
      metadataFormat: oai_ddi
    - url: https://oai-pmh.nsd.no/oai-pmh/
      metadataFormat: oai_ddi
    - url: http://nesstar.sciences-po.fr/oai-pmh/
      metadataFormat: oai_ddi
    - url: http://harvester.sodanet.gr:8080/oai/request?set=CESSDA
      metadataFormat: oai_ddi
    - url: http://nesstar.unidata.unimib.it/oai-pmh/
      metadataFormat: oai_ddi
    - url: http://nesstar.soc.cas.cz/oai-pmh/
      metadataFormat: oai_ddi