#
# @code-generation-comment@
#

version: '3.2'
services:
  restserver:
    image: @docker.registry.uri@/gesis/@project.artifactId@:@project.version@
    ports:
     - @server.port@:@server.port@
#    volumes:
#     - ./application.properties:/@project.artifactId@/application.properties
